dist: xenial
language: python
python:
  - 3.8

before_install:
  - pip install poetry
install:
  - poetry install

script:
  - poetry run inv check.all

deploy:
  provider: script
  script: poetry publish --build
  on:
    tags: true
